import enum


class RoomMemberRole(str, enum.Enum):
    LEADER = "LEADER"
    TEAMMATE = "TEAMMATE"


class RoomMemberState(str, enum.Enum):
    JOINED = "JOINED"
    LEFT = "LEFT"


class TopicStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class UtteranceState(str, enum.Enum):
    REFLECT = "REFLECT"
    NOREFLECT = "NOREFLECT"
    SKIP = "SKIP"


class DialogueMove(str, enum.Enum):
    """발화가 대화에서 수행하는 행위. 판단이 아니라 서술이다."""

    PROPOSE = "PROPOSE"
    DECIDE = "DECIDE"
    ASK = "ASK"
    AGREE = "AGREE"
    DISAGREE = "DISAGREE"
    INFORM = "INFORM"
    OTHER = "OTHER"


class Stance(str, enum.Enum):
    FOR = "FOR"
    AGAINST = "AGAINST"
    NEUTRAL = "NEUTRAL"


class SemanticMemoryType(str, enum.Enum):
    SUMMARY = "SUMMARY"
    DECISION = "DECISION"
    CONSTRAINT = "CONSTRAINT"
    CONFLICT = "CONFLICT"
    RATIONALE = "RATIONALE"


class MemoryStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    SUPERSEDED = "SUPERSEDED"


class DesignFactType(str, enum.Enum):
    PROPOSAL = "PROPOSAL"
    DECISION = "DECISION"
    CONSTRAINT = "CONSTRAINT"
    CONFLICT = "CONFLICT"
    ARGUMENT_FOR = "ARGUMENT_FOR"
    ARGUMENT_AGAINST = "ARGUMENT_AGAINST"
    RATIONALE = "RATIONALE"
    ISSUE = "ISSUE"


class DesignFactStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CONFIRMED = "CONFIRMED"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class DesignFactLinkType(str, enum.Enum):
    SUPPORTS = "SUPPORTS"
    OPPOSES = "OPPOSES"
    CONSTRAINS = "CONSTRAINS"
    CONFLICTS_WITH = "CONFLICTS_WITH"
    RATIONALE_OF = "RATIONALE_OF"
    RESOLVES = "RESOLVES"
    VIOLATES = "VIOLATES"


class DesignFactUtteranceLinkRole(str, enum.Enum):
    SOURCE = "SOURCE"
    SUPPORTING_EVIDENCE = "SUPPORTING_EVIDENCE"
    OPPOSING_EVIDENCE = "OPPOSING_EVIDENCE"
    CONFIRMATION = "CONFIRMATION"
    VIOLATION_TRIGGER = "VIOLATION_TRIGGER"


class NodeType(str, enum.Enum):
    PROPERTY = "PROPERTY"
    REFERENCE = "REFERENCE"
    PART = "PART"


class EdgeType(str, enum.Enum):
    # Edge에는 별도 type 컬럼이 없으므로 기존 reference label 값을 재사용한다.
    PROPERTY_REFERENCE = "REFERENCES"


class AssetType(str, enum.Enum):
    IMAGE_2D = "IMAGE_2D"
    MODEL_3D = "MODEL_3D"
    REFERENCE = "REFERENCE"


class GraphEventType(str, enum.Enum):
    NODE_CREATE = "NODE_CREATE"
    NODE_TEXT_UPDATE = "NODE_TEXT_UPDATE"
    NODE_DELETE = "NODE_DELETE"
    NODE_MOVE = "NODE_MOVE"
    EDGE_CREATE = "EDGE_CREATE"
    EDGE_DELETE = "EDGE_DELETE"
    GENERATE_2D = "GENERATE_2D"


class AlertType(str, enum.Enum):
    """AGENT_GUIDE의 guide_type. 클라이언트 스펙과 이름을 맞춘다."""

    DECISION_CONFLICT = "DECISION_CONFLICT"
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"
    LONG_UNRESOLVED_CONFLICT = "LONG_UNRESOLVED_CONFLICT"
    TOPIC_SHIFT_WITH_UNRESOLVED_CONFLICT = "TOPIC_SHIFT_WITH_UNRESOLVED_CONFLICT"
    DECISION_RATIONALE_RECALL = "DECISION_RATIONALE_RECALL"
    CONSTRAINT_RATIONALE_RECALL = "CONSTRAINT_RATIONALE_RECALL"
    CONFLICT_RATIONALE_RECALL = "CONFLICT_RATIONALE_RECALL"
    SIMILAR_CONFLICT_REPEATED = "SIMILAR_CONFLICT_REPEATED"
    PART_GLOBAL_DECISION_CONFLICT = "PART_GLOBAL_DECISION_CONFLICT"
    # 스펙 밖이지만 기존 데이터가 참조하고 있어 남긴다. 발행되지 않는다.
    GLOBAL_DIRECTION_CONFLICT = "GLOBAL_DIRECTION_CONFLICT"
    PROPOSAL_NOT_INCLUDED_IN_GRAPH = "PROPOSAL_NOT_INCLUDED_IN_GRAPH"
    DECISION_NOT_INCLUDED_IN_GRAPH = "DECISION_NOT_INCLUDED_IN_GRAPH"

class AlertStatus(str, enum.Enum):
    PENDING = "PENDING"
    SHOWN = "SHOWN"
    DISMISSED = "DISMISSED"
    RESOLVED = "RESOLVED"
