# app/models/enums.py

import enum


class RoomMemberRole(str, enum.Enum):
    LEADER = "LEADER"
    TEAMMATE = "TEAMMATE"


class RoomMemberState(str, enum.Enum):
    JOINED = "JOINED"
    LEFT = "LEFT"


class TopicStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class UtteranceState(str, enum.Enum):
    REFLECT = "REFLECT"
    NOREFLECT = "NOREFLECT"


class SemanticMemoryType(str, enum.Enum):
    SUMMARY = "SUMMARY"
    DECISION = "DECISION"
    CONSTRAINT = "CONSTRAINT"
    CONFLICT = "CONFLICT"
    RATIONALE = "RATIONALE"


class MemoryStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"


class DesignFactType(str, enum.Enum):
    PROPOSAL = "PROPOSAL"
    DECISION = "DECISION"
    CONSTRAINT = "CONSTRAINT"
    CONFLICT = "CONFLICT"
    ARGUMENT_FOR = "ARGUMENT_FOR"
    ARGUMENT_AGAINST = "ARGUMENT_AGAINST"
    RATIONALE = "RATIONALE"


class DesignFactStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"


class DesignFactLinkType(str, enum.Enum):
    SUPPORTS = "SUPPORTS"
    OPPOSES = "OPPOSES"
    CONSTRAINS = "CONSTRAINS"
    CONFLICTS_WITH = "CONFLICTS_WITH"
    RATIONALE_OF = "RATIONALE_OF"
    RESOLVES = "RESOLVES"
    VIOLATES = "VIOLATES"


class DesignFactUtteranceLinkRole(str, enum.Enum):
    SOURCE = "SOURCE"
    SUPPORTING_EVIDENCE = "SUPPORTING_EVIDENCE"
    OPPOSING_EVIDENCE = "OPPOSING_EVIDENCE"
    CONFIRMATION = "CONFIRMATION"
    VIOLATION_TRIGGER = "VIOLATION_TRIGGER"


class NodeType(str, enum.Enum):
    PROPERTY = "PROPERTY"
    REFERENCE = "REFERENCE"
    PART = "PART"


class AssetType(str, enum.Enum):
    IMAGE_2D = "IMAGE_2D"
    MODEL_3D = "MODEL_3D"
    REFERENCE = "REFERENCE"


class GraphEventType(str, enum.Enum):
    NODE_CREATED = "NODE_CREATED"
    NODE_UPDATED = "NODE_UPDATED"
    NODE_DELETED = "NODE_DELETED"
    EDGE_CREATED = "EDGE_CREATED"
    EDGE_UPDATED = "EDGE_UPDATED"
    EDGE_DELETED = "EDGE_DELETED"


class AlertType(str, enum.Enum):
    DECISION_VIOLATION = "DECISION_VIOLATION"
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"
    GLOBAL_DIRECTION_CONFLICT = "GLOBAL_DIRECTION_CONFLICT"
    PART_DECISION_CONFLICT = "PART_DECISION_CONFLICT"
    DECISION_RATIONALE_RECALL = "DECISION_RATIONALE_RECALL"
    CONSTRAINT_RATIONALE_RECALL = "CONSTRAINT_RATIONALE_RECALL"
    CONFLICT_ARGUMENT_RECALL = "CONFLICT_ARGUMENT_RECALL"
    LONG_RUNNING_CONFLICT = "LONG_RUNNING_CONFLICT"
    TOPIC_DRIFT_WITH_OPEN_CONFLICT = "TOPIC_DRIFT_WITH_OPEN_CONFLICT"
    PROPOSAL_NOT_INCLUDED_IN_GRAPH = "PROPOSAL_NOT_INCLUDED_IN_GRAPH"
    DECISION_NOT_INCLUDED_IN_GRAPH = "DECISION_NOT_INCLUDED_IN_GRAPH"

class AlertStatus(str, enum.Enum):
    PENDING = "PENDING"
    SHOWN = "SHOWN"
    DISMISSED = "DISMISSED"
    RESOLVED = "RESOLVED"